name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Udskift dette med den branch, du vil deploye fra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Du kan bruge den version af Node.js, som dit projekt kræver

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Sørg for, at denne mappe matcher den genererede build-mappe
